name: Release Build

on:
  push:
    branches: [ "master" ]
    tags:
      - 'beta'

jobs:
  build:
    strategy:
      matrix:
        goos: [ windows, linux ]
        goarch: [ amd64, 386 ]
        goamd64: [ v1 ]
        exclude:
          - goarch: 386
            goos: dragonfly

    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOAMD64: ${{ matrix.goamd64 }}
      CGO_ENABLED: 0
      BUILD_NAME: AutoInstall-${{ matrix.goos }}-${{ matrix.goarch }}-${{ matrix.goamd64 }}${{ matrix.goos == 'windows' && '.exe' || '' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.20
          check-latest: true

      - name: Build
        run: bash ./build.sh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}
          path: dist/${{ env.BUILD_NAME }}

  release:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ windows, linux ]
        goarch: [ amd64, 386 ]
        goamd64: [ v1 ]
        exclude:
          - goarch: 386
            goos: dragonfly
    env:
      BUILD_NAME: AutoInstall-${{ matrix.goos }}-${{ matrix.goarch }}-${{ matrix.goamd64 }}${{ matrix.goos == 'windows' && '.exe' || '' }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Beta Release"
          tag_name: beta
          body: |
            Beta release generated from commit ${{ github.sha }}
          prerelease: true
          files: dist/${{ env.BUILD_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}