name: Release Build

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        goos: [ linux ]
        goarch: [ amd64, 386 , arm64 , arm]
        goamd64: [ v1 ]
        exclude:
          - goarch: 386
            goos: dragonfly

    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOAMD64: ${{ matrix.goamd64 }}
      CGO_ENABLED: 0
      BUILD_NAME: AutoInstall-${{ matrix.goos }}-${{ matrix.goarch }}-${{ matrix.goamd64 }}${{ matrix.goos == 'windows' && '.exe' || '' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.20

      - name: Build
        run: bash ./build.sh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}
          path: dist/${{ env.BUILD_NAME }}